In [1]:
import pandas as pd

df = pd.read_csv("../data/casen_sintetico.csv")
df.head()

,genero,edad,region,nivel_educacion,sector_economico,situacion_laboral,ingreso_mensual
0,Hombre,15,Metropolitana,Básica,NaN,Inactivo,NaN
1,Mujer,60,Valparaíso,Técnica,NaN,Inactivo,NaN
2,Hombre,60,Arica y Parinacota,Básica,Industria,Ocupado,466000.0
3,Hombre,34,Coquimbo,Universitaria,Comercio,Ocupado,611000.0
4,Mujer,50,Ñuble,Universitaria,NaN,Inactivo,NaN

In [2]:
df["ocupado"] = df["situacion_laboral"] == "Ocupado"
df[["situacion_laboral", "ocupado"]].head()

  situacion_laboral  ocupado
0          Inactivo    False
1          Inactivo    False
2           Ocupado     True
3           Ocupado     True
4          Inactivo    False

In [3]:
df.groupby("situacion_laboral")["ingreso_mensual"].apply(lambda x: x.isna().sum())

situacion_laboral
Desocupado     648
Inactivo      3326
Ocupado          0
Name: ingreso_mensual, dtype: int64

In [4]:
df.to_csv("../data/casen_limpio.csv", index=False)
print("Archivo guardado en data/casen_limpio.csv")

Archivo guardado en data/casen_limpio.csv